# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :node1 do |node1|
    node1.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node1.vm.network :private_network, ip: "192.168.56.101"
    node1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "node1" ]
    end
  end
  config.vm.define :node2 do |node2|
    node2.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node2.vm.network :private_network, ip: "192.168.56.102"
    node2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "node2" ]
    end
  end
  config.vm.define :node3 do |node3|
    node3.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node3.vm.network :private_network, ip: "192.168.56.103"
    node3.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "node3" ]
    end
  end
end